# report_pdf.py
import io
import numpy as np

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm

# Optional plot embedding
try:
    import matplotlib.pyplot as plt
    HAS_MPL = True
except Exception:
    HAS_MPL = False


def _t(lang: str, en: str, ar: str) -> str:
    return en if lang == "en" else ar


def _draw_multiline(c, x, y, lines, line_height=14):
    for line in lines:
        c.drawString(x, y, str(line))
        y -= line_height
    return y


def _make_plot_png(df_out):
    """
    Returns PNG bytes for a simple plot (MAP, HR, SpO2, risk_score).
    If matplotlib not available, returns None.
    """
    if not HAS_MPL:
        return None

    cols = [c for c in ["MAP", "HR", "SpO2", "risk_score"] if c in df_out.columns]
    if len(cols) == 0:
        return None

    fig = plt.figure()
    for c in cols:
        plt.plot(df_out[c].values, label=c)
    plt.legend()
    plt.title("Vitals & Risk")
    plt.xlabel("Index")
    plt.ylabel("Value")

    bio = io.BytesIO()
    fig.savefig(bio, format="png", bbox_inches="tight", dpi=140)
    plt.close(fig)
    bio.seek(0)
    return bio.getvalue()


def generate_pdf_report(df_out, patient_info: dict, explanation: dict, threshold: float, drop_text: str, lang: str = "en"):
    """
    Returns PDF bytes.
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Header
    c.setFont("Helvetica-Bold", 14)
    c.drawString(2 * cm, height - 2 * cm, _t(lang, "Hypotension Early Warning Report", "تقرير الإنذار المبكر لهبوط الضغط"))

    c.setFont("Helvetica", 10)
    c.drawString(2 * cm, height - 2.7 * cm, _t(lang, "Decision-support report generated by the dashboard.", "تقرير مساند للقرار تم توليده من لوحة التحكم."))

    y = height - 3.6 * cm

    # Patient Info
    c.setFont("Helvetica-Bold", 12)
    c.drawString(2 * cm, y, _t(lang, "Patient Info", "بيانات المريض"))
    y -= 0.6 * cm

    c.setFont("Helvetica", 10)
    info_lines = [
        f"{_t(lang,'Patient ID','معرّف المريض')}: {patient_info.get('Patient ID','')}",
        f"{_t(lang,'Age','العمر')}: {patient_info.get('Age','')}",
        f"{_t(lang,'Sex','الجنس')}: {patient_info.get('Sex','')}",
        f"{_t(lang,'ICU/OR','الموقع')}: {patient_info.get('ICU/OR','')}",
        f"{_t(lang,'Drop Type','نوع الهبوط')}: {drop_text}",
        f"{_t(lang,'Threshold','العتبة')}: {threshold:.2f}",
    ]
    y = _draw_multiline(c, 2 * cm, y, info_lines, line_height=13)
    y -= 0.4 * cm

    # Summary
    last = df_out.iloc[-1] if df_out is not None and len(df_out) else None
    if last is not None:
        MAP = float(last.get("MAP", np.nan))
        HR = float(last.get("HR", np.nan))
        SpO2 = float(last.get("SpO2", np.nan))
        risk = float(last.get("risk_score", np.nan))
        alarm = bool(last.get("alarm", False))

        c.setFont("Helvetica-Bold", 12)
        c.drawString(2 * cm, y, _t(lang, "Model Output", "مخرجات النموذج"))
        y -= 0.6 * cm

        c.setFont("Helvetica", 10)
        out_lines = [
            f"{_t(lang,'Latest MAP','آخر MAP')}: {MAP:.1f}" if np.isfinite(MAP) else f"{_t(lang,'Latest MAP','آخر MAP')}: -",
            f"{_t(lang,'Latest HR','آخر HR')}: {HR:.0f}" if np.isfinite(HR) else f"{_t(lang,'Latest HR','آخر HR')}: -",
            f"{_t(lang,'Latest SpO2','آخر SpO2')}: {SpO2:.0f}%" if np.isfinite(SpO2) else f"{_t(lang,'Latest SpO2','آخر SpO2')}: -",
            f"{_t(lang,'Risk Score','درجة الخطر')}: {risk:.3f}" if np.isfinite(risk) else f"{_t(lang,'Risk Score','درجة الخطر')}: -",
            f"{_t(lang,'Alarm','إنذار')}: {'YES' if alarm else 'NO'}",
        ]
        y = _draw_multiline(c, 2 * cm, y, out_lines, line_height=13)
        y -= 0.4 * cm

    # Explanation
    c.setFont("Helvetica-Bold", 12)
    c.drawString(2 * cm, y, _t(lang, "Automated Explanation", "تفسير آلي"))
    y -= 0.6 * cm

    c.setFont("Helvetica", 10)
    y = _draw_multiline(c, 2 * cm, y, [explanation.get("headline", "")], line_height=13)
    y -= 0.2 * cm

    c.setFont("Helvetica-Bold", 10)
    c.drawString(2 * cm, y, explanation.get("reasons_title", _t(lang, "Why?", "لماذا؟")))
    y -= 0.4 * cm

    c.setFont("Helvetica", 10)
    for r in explanation.get("reasons", [])[:10]:
        y = _draw_multiline(c, 2.2 * cm, y, [f"• {r}"], line_height=12)
        if y < 4 * cm:
            c.showPage()
            y = height - 2 * cm

    y -= 0.2 * cm
    c.setFont("Helvetica-Bold", 10)
    c.drawString(2 * cm, y, explanation.get("rec_title", _t(lang, "Recommendation", "التوصيات")))
    y -= 0.4 * cm

    c.setFont("Helvetica", 10)
    for r in explanation.get("recommendation", [])[:10]:
        y = _draw_multiline(c, 2.2 * cm, y, [f"• {r}"], line_height=12)
        if y < 4 * cm:
            c.showPage()
            y = height - 2 * cm

    # Plot (optional)
    png = _make_plot_png(df_out)
    if png is not None:
        if y < 10 * cm:
            c.showPage()
            y = height - 2 * cm

        c.setFont("Helvetica-Bold", 12)
        c.drawString(2 * cm, y, _t(lang, "Plots", "الرسوم"))
        y -= 0.6 * cm

        from reportlab.lib.utils import ImageReader
        img = ImageReader(io.BytesIO(png))
        c.drawImage(img, 2 * cm, y - 8 * cm, width=17 * cm, height=8 * cm, preserveAspectRatio=True, mask="auto")
        y -= 8.4 * cm

    # Disclaimer
    if y < 4 * cm:
        c.showPage()
        y = height - 2 * cm

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(2 * cm, y, explanation.get("disclaimer", _t(lang, "Disclaimer: decision support only.", "تنبيه: للمساعدة فقط.")))

    c.save()
    buffer.seek(0)
    return buffer.getvalue()
